article/urls.py
from django.contrib import admin
from django.urls import path
from .views import ArticleDetail

app_name = "article"
urlpatterns = [
    path("<int:pk>/", ArticleDetail.as_view(), name="article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

urlpatterns = [
    path(settings.ADMIN_PATH + "/", admin.site.urls),
    path("cup/", include("main.urls")),
    path("article/", include("article.urls")),
    path(r'mdeditor/', include('mdeditor.urls')),
    path("", lambda request: redirect("cup/")),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from .views import CupListView, TopView, AboutView, OwnerView, PrivacyView

app_name = "cup"
urlpatterns = [
    path("list/", CupListView.as_view(), name="list"),
    path("about/", AboutView.as_view(), name="about"),
    path("owner/", OwnerView.as_view(), name="owner"),
    path("privacy/", PrivacyView.as_view(),name="privacy"),
    path("", TopView.as_view(), name="top"),
    # path("error/",ErrorView.as_view()),
]

article/models.py
from django.db import models
from mdeditor.fields import MDTextField
import markdown


# Create your models here.

class Article(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=100)
    meta_description = models.CharField(verbose_name="ディスクリプション", max_length=150, blank=True, null=True)
    content = MDTextField()

    def __str__(self):
        return self.title

    def markdown_to_html(self):
        md = markdown.Markdown(
            extensions=['extra', 'admonition', 'sane_lists', 'toc']
        )
        html = md.convert(self.content)
        return html

main/models.py
from django.db import models
from django.core.exceptions import ValidationError


def validate_value(value):
    if value not in ['rakuten', 'yahoo']:
        raise ValidationError(f"{value} is not a valid value.")


# Create your models here.
class Item(models.Model):
    name = models.CharField(verbose_name="商品名", max_length=500)
    price = models.BigIntegerField(verbose_name="価格")
    caption = models.TextField(verbose_name="商品紹介", max_length=1000)
    item_url = models.CharField(verbose_name="商品URL",
                                max_length=500)
    item_code = models.CharField(verbose_name="アイテムコード", max_length=500)
    image_url = models.CharField(verbose_name="画像URL", max_length=500)
    image = models.ImageField(verbose_name="商品画像", upload_to="item_images/")
    capacity = models.BigIntegerField(verbose_name="容量", default=0)
    seller = models.CharField(verbose_name="販売サイト", max_length=100, validators=[validate_value])
    rank = models.BigIntegerField(verbose_name="順位", default=0)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "items"
        verbose_name = verbose_name_plural = "商品"

main/forms.py
from django.forms import (
    forms,
    CharField,
    IntegerField
)


class TopForm(forms.Form):
    """ トップページ用のフォーム　"""
    min = IntegerField(label="最低容量", min_value=50, max_value=900, required=False)
    max = IntegerField(label="最低容量", min_value=100, max_value=1000, required=False)
    search_word = CharField(label="検索単語", max_length=20, required=False)

article/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from article.models import Article


# Create your views here.
class ArticleDetail(DetailView):
    model = Article
    context_object_name = "article"
    template_name = "article/article.html"

main/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView, TemplateView
from .models import Item
from django.http import Http404
from .forms import TopForm
from django.urls import reverse
import urllib.parse
from django.db.models import Q


def createUrlPagination(request):
    '''
    目的：検索クエリを残しながら、ページネーションのpageだけ抜いたURLを返す
    入力：request => djangoのrequestオブジェクト
    出力：urlForPagination => string
    '''
    url = request.build_absolute_uri()
    pr = urllib.parse.urlparse(url)
    d = urllib.parse.parse_qs(pr.query)
    d.pop("page", None)
    return urllib.parse.urlunparse(pr._replace(query=urllib.parse.urlencode(d, doseq=True)))


def conditionFromRange(min: int, max: int, field: str):
    if min and max:
        if min < max:
            dict_q = {f"{field}__range": (min, max)}
            condition = Q(**dict_q)
        else:
            raise Http404("サイズの指定方法に誤りがあります")
    elif min:
        dict_q = {f"{field}__gte": min}
        condition = Q(**dict_q)
    elif max:
        dict_q = {f"{field}__lte": max}
        condition = Q(**dict_q)
    else:
        condition = None

    return condition


def conditionFromRequet(request):
    """
    目的：requestのクエリからItemオブジェクトをソート・検索する
    入力：request => djangoのrequestオブジェクト
    出力：condition => djangoのQオブジェクト
    """
    dict_int_query = {
        "min_capacity": 0,
        "max_capacity": 0,
        "min_price": 0,
        "max_price": 0,
    }
    for key in dict_int_query.keys():
        dict_int_query[key] = request.GET.get(key)
        dict_int_query[key] = None if not dict_int_query[key] else int(dict_int_query[key])

    search_material = request.GET.get("search_material")
    search_material = None if not search_material else str(search_material)

    # サイズの検索
    condition_size = conditionFromRange(
        min=dict_int_query["min_capacity"],
        max=dict_int_query["max_capacity"],
        field="capacity"
    )
    # 価格の検索
    condition_price = conditionFromRange(
        min=dict_int_query["min_price"],
        max=dict_int_query["max_price"],
        field="price"
    )
    # 単語検索
    if search_material:
        condition_material = Q(name__icontains=search_material)
    else:
        condition_material = None

    # 結合用に空のQオブジェクトを作成
    conditions = Q()
    condition_all = [condition_size, condition_price, condition_material]
    for condition in condition_all:
        if condition != None:
            conditions &= condition

    return conditions


def validationURLQuery(request):
    '''
    目的：URLクエリのValidationを実行し、不正なクエリは404エラーを返す
    チェック項目：
    ・int型のクエリは正の整数か
    ・sortに禁止文字が使われていないか
    ・10,000,000を超える値
    ・search_materialが250文字超える
    入力:request -> djangoのrequestオブジェクト
    出力：なし
    '''

    list_int_query = ["min_capacity", "max_capacity", "min_price", "max_price"]
    # 整数もしくは、10,000,000を超えないか
    for query in list_int_query:
        parameter = request.GET.get(query)
        if not (parameter is None):
            if not parameter.isdigit():
                raise Http404("URLの指定方法に誤りがあります")
            if int(parameter) >= 10000000:
                raise Http404("URLの指定方法に誤りがあります")

    # sortが禁止文字か
    permission_sort_word = ["capacity", "price"]
    parameter = request.GET.get("sort")
    if not (parameter is None):
        if not parameter in permission_sort_word:
            raise Http404("URLの指定方法に誤りがあります")

    # search_material250文字を超えるか
    parameter = request.GET.get("search_material")
    if not (parameter is None):
        if len(parameter) >= 240:
            raise Http404("URLの指定方法に誤りがあります")


class TopView(TemplateView):
    template_name = "main/top.html"


class CupListView(ListView):
    template_name = "main/list.html"
    model = Item
    context_object_name = "items"
    paginate_by = 12

    def get(self, request, *args, **kwargs):
        '''URLクエリのValidationを実施'''
        validationURLQuery(self.request)
        return super().get(self, request, *args, **kwargs)

    def get_queryset(self):
        # URLのクエリパラメータからQオブジェクトを取得
        Q_conditions = conditionFromRequet(self.request)
        query = Item.objects.filter(Q_conditions)
        # ソート条件で並び替え
        if self.request.GET.get("sort"):
            sort_key = self.request.GET.get("sort")
            query = query.order_by(sort_key)
        else:
            query = query.order_by("rank", "item_code")
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        urlForPagination = createUrlPagination(self.request)
        extra = {"urlForPagination": urlForPagination}
        context.update(extra)
        return context


class AboutView(TemplateView):
    template_name = "main/about.html"


class OwnerView(TemplateView):
    template_name = "main/owner.html"


class PrivacyView(TemplateView):
    template_name = "main/privacy.html"

templates/article/article.html
{% extends "base.html" %}
{% load static %}
<!-- meta -->
{% block meta %}
<link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:title" content="マグカップサイズサーチ > {{ article.title }} | マグカップやコップをサイズ・容量・大きさから探そう"/>
<meta property="og:description" content="{{ article.meta_description |default:'マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。' }}"/>
<meta content="{{ article.meta_description |default:'マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。' }}" name="description">
<meta property="og:url" content="https://www.mug-cup.tokyo/cup/owner/"/>
<meta property="og:type" content="website" />
<meta property="og:site_name" content="マグカップサイズサーチ" />
<meta property="og:locale" content="ja_JP"  />
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'main\sass\article.css' %}">
{% endblock %}
{% block title %}マグカップサイズサーチ > {{ article.title }} | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}
{% block content %}
    <div class="main wrapper">
        <div class="article">
            {{ article.markdown_to_html | safe }}
        </div>
    </div>
    <script src="https://kit.fontawesome.com/d6ddb93240.js" crossorigin="anonymous"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    {#  ファビコン  #}
    <link rel="icon" type="image/svg+xml" href="{% static 'favicon.svg' %}">
    {#  電話番号無効化  #}
    <meta name="format-detection" content="telephone=no">
    <title>{% block title%}{% endblock %}</title>
    {% include "header.html" %}
    {% block meta %}
    {% endblock %}
    {% block css %}
    {% endblock %}
    {% block script %}
    {% endblock %}
</head>
<body>
<div class="container">
{#    {% include "parts/head.html" %}#}
    {% include "head.html" %}
    {% block content %}
    {% endblock %}
{#    {% include "parts/footer.html" %}#}
    {% include "footer.html" %}
</div>
</body>
</html>

templates/footer.html
<footer>
    <div class="footer">
        <div class="link">
{#            <a href="#" class="owner-link">利用規約</a>#}
            <a href="{% url 'cup:privacy' %}" class="owner-link">プライバシーポリシー</a>
            <a href="{% url 'cup:about' %}" class="about-link">当サイトについて</a>
            <a href="{% url 'cup:owner' %}" class="owner-link">運営者・お問い合わせ先</a>
        </div>
        <p><small>&copy; 2023 Kato</small></p>
    </div>
</footer>

templates/head.html
{% load static %}
<header id="header">
    <div class="header-title">
        <a href="{% url 'cup:top' %}">
        <div class="header-logo">
            <img src="{% static 'coffe_logo.png' %}" alt="" class="header-img">
            <div class="header-text">
                <h1 class="header-h1">
                    マグカップサイズサーチ
                </h1>
                <h2 class="header-msg">
                    サイズ・容量・大きさからコップやマグカップを検索しよう
                </h2>
            </div>
        </div>
        </a>
    </div>
</header>

templates/header.html
{% load static %}
<link rel="stylesheet" href='{% static "reset.css" %}'>
<link rel="stylesheet" href='{% static "main\base.css" %}'>
<link rel="stylesheet" href='{% static "main\sass\footer.css" %}'>
<link rel="stylesheet" href='{% static "main\header.css" %}'>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4KL4GJY0DD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4KL4GJY0DD');
</script>

templates/js.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.11"></script>
<script src="https://kit.fontawesome.com/d6ddb93240.js" crossorigin="anonymous"></script>

templates/main/about.html
{% extends "base.html" %}
{% load static %}
<!-- meta -->
{% block meta %}
<link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:title" content="マグカップサイズサーチ > 当サイトについて | マグカップやコップをサイズ・容量・大きさから探そう"/>
<meta property="og:description" content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"/>
<meta content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。" name="description">
<meta property="og:url" content="https://www.mug-cup.tokyo/cup/about/"/>
<meta property="og:type" content="website" />
<meta property="og:site_name" content="マグカップサイズサーチ" />
<meta property="og:locale" content="ja_JP"  />
{% endblock %}
{% block css %}
    <link rel="stylesheet" href='{% static "main\list.css" %}'>
    <link rel="stylesheet" href="{% static 'main\sass\about.css' %}">
{% endblock %}
{% block title %}マグカップサイズサーチ > 当サイトについて | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}
{% block content %}
    <div class="main wrapper">
        <div class="about">
            <h2>当サイトについて</h2>
            <div class="text">
                <p>
                    マグカップサイズサーチは、容量やサイズから<br>コップやマグカップを検索できるサービスです。
                </p>
                <div class="dialogue">
                    <p>「珈琲や紅茶に丁度いいカップを探したい」</p>
                    <p>「いやいや、大きいマグカップを見つけたい」</p>
                    <p>「日常遣いできるサイズでおしゃれなものはないかな」</p>
                </div>
                <p>
                    そんなコップやマグカップを探している方に向けたサービスです。
                </p>
                <p>容量やサイズを確認しながら、あなたにぴったりなマグカップを見つけるお手伝いをします。</p>
                <p>ぜひマグカップサイズサーチを使って、お気に入りのカップを見つけてください。</p>
            </div>
            <div class="about-image">
                <img src="{% static 'coffe_image.jpg' %}" alt="coffe_image">
            </div>
        </div>
    </div>
    <script src="https://kit.fontawesome.com/d6ddb93240.js" crossorigin="anonymous"></script>
{% endblock %}

templates/main/list.html
{% extends "base.html" %}
{% load static %}
{% load url_filter %}
<!-- meta -->
{% block meta %}
<link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:title" content="マグカップサイズサーチ > 検索結果 | マグカップやコップをサイズ・容量・大きさから探そう"/>
<meta property="og:description" content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"/>
<meta content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。" name="description">
<meta property="og:url" content="https://www.mug-cup.tokyo/cup/list/"/>
<meta property="og:type" content="website" />
<meta property="og:site_name" content="マグカップサイズサーチ" />
<meta property="og:locale" content="ja_JP"  />
<meta name="robots" content="noindex,nofollow">
{% endblock %}
{% block css %}
    <link rel="stylesheet" href='{% static "main\list.css" %}'>
    <link rel="stylesheet" href='{% static "main\pagination.css" %}'>
    <link rel="stylesheet" href='{% static "main\modal.css" %}'>
{% endblock %}
{% block title %}マグカップサイズサーチ > 検索結果 | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}
{% block script %}
    {% include "modal.html" %}
{% endblock %}
{% block content %}
    <div id="app">
        <div class="main wrapper">
            <div class="modal">
                <button id="show-modal" @click="showModal = true" class="modal-button"><i class="fa-solid fa-sliders"></i>絞り込み</button>
                <!-- use the modal component, pass in the prop -->
                <modal v-if="showModal" @close="showModal = false">
                </modal>

            </div>
            <div class="condition" v-clock>
                <div class="condition-caption">
                    <p>絞り込み条件：</p>
                </div>
                <div class="condition-list">
                    <div class="condition-price" v-if="min_price !== null | max_price !== null">
                        <p>[[ min_price ]]～[[ max_price ]]円</p>
                    </div>
                    <div class="condition-capacity" v-if="min_capacity !== null | max_capacity !== null">
                        <p>[[ min_capacity ]]～[[ max_capacity ]]ml</p>
                    </div>
                    <div class="condition-material" v-if="search_material !== null">
                        <p> 検索：[[ search_material ]]</p>
                    </div>
                    <div class="condition-sort" v-if="sort !== null">
                        <p>[[ sort ]]</p>
                    </div>
                </div>
            </div>
            <div class="list grid">
                {% for item in items %}
                    <div class="list-item">
                        {% if item.image %}
                            <div class="list-image"><img src="{{ item.image.url }}" alt=""></div>
                        {% endif %}
                        <div class="list-info">
                            <p class="list-title">{{ item.name |truncatechars:45 }}</p>
                            <p class="capacity">容量 <span>{{ item.capacity }}ml</span></p>
                            <p class="price">値段 <span>{{ item.price }}円</span></p>
                            {% if item.seller == "rakuten" %}
                                <a href="{{ item.item_url }}" target="_blank" rel="noopener noreferrer" class="rakuten-url">商品はこちら</a>
                            {% elif item.seller == "yahoo" %}
                                <a href="{{ item.item_url }}" target="_blank" rel="noopener noreferrer" class="yahoo-url">商品はこちら</a>
                            {% else %}
                                <a href="{{ item.item_url }}" target="_blank" rel="noopener noreferrer">商品はこちら</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            {# /list #}
            {% include "pagination.html" %}
        </div>
    </div>
    {% include "js.html" %}
    <script src="{% static 'main/js/list.js' %}"></script>
{% endblock %}

templates/main/owner.html
{% extends "base.html" %}
{% load static %}
<!-- meta -->
{% block meta %}
    <link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
    <meta property="og:title" content="マグカップサイズサーチ > 運営者 | マグカップやコップをサイズ・容量・大きさから探そう"/>
    <meta property="og:description"
          content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"/>
    <meta content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"
          name="description">
    <meta property="og:url" content="https://www.mug-cup.tokyo/cup/owner/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="マグカップサイズサーチ"/>
    <meta property="og:locale" content="ja_JP"/>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href='{% static "main\list.css" %}'>
    <link rel="stylesheet" href="{% static 'main\sass\owner.css' %}">
{% endblock %}
{% block title %}マグカップサイズサーチ> 運営者 | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}
{% block content %}
    <div class="main wrapper">
        <div class="owner">
            <h2>運営者</h2>
            <div class="text">
                <p>
                    東京都在住の20台後半(ほぼ30です)。
                    職業はインフラエンジニアです。
                </p>
                <p>
                    インスタンスコーヒーの140mlを見て厳密に守るかというと守らないです。<br>
                    ココアやコーンスープは濃い目に作りたいので小さめのカップを使います。
                </p>

                <p>ちなみに、レトロの喫茶店の一杯は150mlぐらいですが、<br>
                    スターバックスのグランデは470mlもあるようです。</p>
                <p>それを考えると、スターバックスが良心的に思えてきますね。</p>
            </div>
            <div class="owner">
                <p>質問やお問い合わせについては、運営者のtwitterからご連絡ください。</p>
                <a href="https://twitter.com/infrakato" class="twitter" target="_blank">
                    <div class="name">運営者のtwitter</div>
                    <i class="fa-brands fa-square-twitter"></i>
                </a>
            </div>
        </div>
    </div>
    <script src="https://kit.fontawesome.com/d6ddb93240.js" crossorigin="anonymous"></script>
{% endblock %}

templates/main/privacy.html
{% extends "base.html" %}
{% load static %}
<!-- meta -->
{% block meta %}
<link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:title" content="マグカップサイズサーチ > プライバシーポリシー | マグカップやコップをサイズ・容量・大きさから探そう"/>
<meta property="og:description" content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"/>
<meta content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。" name="description">
<meta property="og:url" content="https://www.mug-cup.tokyo/cup/owner/"/>
<meta property="og:type" content="website" />
<meta property="og:site_name" content="マグカップサイズサーチ" />
<meta property="og:locale" content="ja_JP"  />
{% endblock %}
{% block css %}
    <link rel="stylesheet" href='{% static "main\list.css" %}'>
    <link rel="stylesheet" href="{% static 'main\sass\privacy.css' %}">
{% endblock %}
{% block title %}マグカップサイズサーチ > プライバシーポリシー | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}
{% block content %}
    <div class="main wrapper">
        <div class="privacy">
            <h2>プライバシーポリシー</h2>
            <div class="text">
                <div class="terms">
                    当社が提供するサービス（以下「本サービス」といいます。）における、本サービスを利用する皆様（以下「ユーザー」といいます。）の個人情報の取扱いについて、以下のとおりプライバシーポリシーを定め、その保護に万全を尽くします。
                </div>
                <div class="terms">
                    <h3>Cookie</h3>
                    <p>
                        当サイトではログイン状態の確認、サイトの分析と改善のためにCookieを利用しています。
                        トラフィックデータ収集にはGoogle Analyticsが使用されています。
                        ユーザーはブラウザの設定によりCookieの送信を拒否することができます。
                        データは匿名で収集されており、個人を特定するものではありません。
                        この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。
                        この規約に関して、<a href="https://marketingplatform.google.com/about/analytics/terms/jp/" target="_blank">ここをクリック</a>詳しくはしてください。</p>
                </div>
                <div class="terms">
                    <h3>個人情報の開示について</h3>
                    <p>
                        取得した情報は、次のような場合を除いて第三者に開示することはありません。
                    </p>
                    <ul>
                        <li>ユーザー本人の同意がある場合</li>
                        <li>開示すべき法的義務を負っている場合</li>
                        <li>不正利用があった場合</li>
                        <li>運営の権利や財産を保護するために必要と、運営が合理的に判断した場合</li>
                    </ul>


                </div>
            </div>
        </div>
    </div>
    <script src="https://kit.fontawesome.com/d6ddb93240.js" crossorigin="anonymous"></script>
{% endblock %}

templates/main/top.html
{% extends "base.html" %}
{% load static %}
<!-- meta -->
{% block meta %}
<link rel="canonical" href="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:title" content="マグカップサイズサーチ | マグカップやコップをサイズ・容量・大きさから探そう"/>
<meta property="og:description" content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。"/>
<meta content="マグカップやコップをサイズ・容量・大きさから検索することができます。大容量のコップやコーヒーにぴったりなマグカップを見つけたいときに向いています。" name="description">
<meta property="og:url" content="https://www.mug-cup.tokyo/cup/"/>
<meta property="og:type" content="website" />
<meta property="og:site_name" content="マグカップサイズサーチ" />
<meta property="og:locale" content="ja_JP"  />
{% endblock %}
{% block css %}
    <link rel="stylesheet" href='{% static "main\top.css" %}'>
    <link rel="stylesheet" href="{% static 'main/swiper/swiper-bundle.min.css' %}">
{% endblock %}
{% block title %}マグカップサイズサーチ | マグカップやコップをサイズ・容量・大きさから探そう{% endblock %}

{% block content %}
    <div class="main wrapper" id="top">
        <div class="caption">
            <p><span>サイズ</span>と<span>素材</span>を選んで<br>コップ・マグカップを検索しよう</p>
            <br>
            <div class="caption-sub">
            <p>サイトを横断して探すことができます</p>
            </div>
        </div>
        <!-- Slider main container -->
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <a href="{% url 'article:article' 1 %}" class="swiper-slide" target="_blank">
                    <div class="hero-title">サイズの選び方</div>
                    <img src="{% static 'swiper/top-image-1.jpg' %}" alt="">
                </a>
                <a href="{% url 'cup:about' %}" class="swiper-slide" target="_blank">
                    <div class="hero-title">サイトについて</div>
                    <img src="{% static 'swiper/top-image-2.jpg' %}" alt="">
                </a>
                <a href="{% url 'cup:owner' %}" class="swiper-slide" target="_blank">
                    <div class="hero-title">運営者について</div>
                    <img src="{% static 'swiper/top-image-3.jpg' %}" alt="">
                </a>
            </div>

        </div>
        <div class="size">
            <div class="size-head head">
                <h2 class="size-h2">
                    <img src="{% static 'measure.png' %}" alt="" class="size-img icon">
                    サイズ
                </h2>
            </div>
            <div class="size-selects">
                <button name="size-select" type="button" v-on:click="changeSizeBool('small')"
                        v-bind:class="{activeSize:isSmall}">
                    140～250ml<br><span>喫茶店のように飲むならこのサイズ</span>
                </button>
                <button name="size-select" type="button" v-on:click="changeSizeBool('medium')"
                        v-bind:class="{activeSize:isMedium}">
                    250～400ml<br><span>日常づかいにピッタリな定番サイズ</span>
                </button>
                <button name="size-select" type="button" v-on:click="changeSizeBool('large')"
                        v-bind:class="{activeSize:isLarge}">
                    400～600ml<br><span>たっぷりと注ぎたいならこのサイズ</span>
                </button>
            </div>
        </div>
        <div class="material">
            <div class="material-head head">
                <h2 class="material-h2">
                <img src="{% static 'material.png' %}" alt="" class="material-img icon">
                    検索したい素材
                </h2>
            </div>
            <div class="material-selects">
                <button name="material-select-1" type="button" v-on:click="changeMaterialBool('mug')"
                        v-bind:class="{activeMaterial:isMug}">
                    マグカップ
                </button>
                <button name="material-select-2" type="button" v-on:click="changeMaterialBool('glass')"
                        v-bind:class="{activeMaterial:isGlass}">
                    グラス
                </button>
                <button name="material-select-3" type="button" v-on:click="changeMaterialBool('stainless')"
                        v-bind:class="{activeMaterial:isStainless}">
                    ステンレス
                </button>
            </div>
        </div>
        <div class="search">
            <a v-bind:href="[[ searchUrl ]]" class="search-btn" v-bind:class="{isSearch:isSearch}">
                <i class="fa-solid fa-magnifying-glass"></i>
                検索
            </a>
        </div>
    </div>
    {% include "js.html" %}
    <script src="{% static 'main/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'main/js/top.js' %}"></script>
{% endblock %}